=== antonio0354/EjerciciosCiclo/kkLMSGI/src/dtdejercicio2tema4.dtd
<!ELEMENT correosElectronicos (correo*)>
	<!ELEMENT correo (destinatario+,asunto,cuerpo,archivos*)>
	<!ELEMENT destinatario (para | cc | cco )>
	<!ELEMENT asunto (#PCDATA)>
	<!ELEMENT cuerpo (#PCDATA)>
	<!ELEMENT archivos (nombre,type,longitud)>
	<!ELEMENT para (#PCDATA)>
	<!ELEMENT cc (#PCDATA)>
	<!ELEMENT cco (#PCDATA)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT type (#PCDATA)>
	<!ELEMENT longitud (#PCDATA)>

=== antonio0354/EjerciciosCiclo/kkLMSGI/src/ejercicio2tema4.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE correosElectronicos SYSTEM "dtdejercicio2tema4.dtd">
	

<correosElectronicos>
	<correo>
		<destinatario><para>Jos√©</para></destinatario>
		<destinatario><cc>Antonio</cc></destinatario>
		<destinatario><cc>Javier</cc></destinatario>
		<asunto>yieee</asunto>
		<cuerpo>hola que ase </cuerpo>
		<archivos>
			<nombre>ei.jpg</nombre>
			<type>image/jpeg</type>
			<longitud>8596KB</longitud>
		</archivos>
	</correo>
</correosElectronicos>
