=== antonio0354/EjerciciosCiclo/kkLMSGI/src/dtdejericio1tema4.dtd
<!ELEMENT placas (placa*)>
	<!ELEMENT placa (microprocesador?, memoria?, modelo?, fabricante?)*>
	<!ELEMENT microprocesador (#PCDATA)>
	<!ELEMENT memoria (#PCDATA)>
	<!ELEMENT modelo (#PCDATA)>
	<!ELEMENT fabricante (Asus | Intel)>
	<!ELEMENT Asus EMPTY>
	<!ELEMENT Intel EMPTY>

=== antonio0354/EjerciciosCiclo/kkLMSGI/src/Ejercicio1tema4.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE placas SYSTEM "dtdejericio1tema4.dtd">

<placas>
	<placa>
		<microprocesador>hola </microprocesador>
		<memoria> 64GB</memoria>
		<memoria> 64GB</memoria>
		<modelo>AMD </modelo>
		<fabricante><Asus/></fabricante>
	</placa>
	<placa>
		<microprocesador>adios </microprocesador>
		<memoria> 32GB</memoria>
		<modelo>AMD </modelo>
		<fabricante><Intel/></fabricante>
	</placa>
</placas>
